### ISSUE TITLE
Setting the image width

### ISSUE THREAD

**Issue by TBSten** [hayato-osh/copy-lgtm#67]
## Why

I felt the LGTM image was too large and overpowered the comment section.

**Comment by hayato-osh** [comment]
@TBSten 
Sorry for the late reply and thanks for your feedback!
I do feel it's a bit too large, so I'll update it in the next minor update!

**Comment by hayato-osh** [comment]
It has been released as 2.4.0 and is closed.
Thank you very much!
https://github.com/hayato-osh/copy-lgtm/releases/tag/2.4.0
